appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pnjxMM4G7oYHLaF56wKUK25AlrlWoDghE9QP427isacywCDorxsxZj9YFer5ITNRMaTN/Q9fWAsqVlcvmogNi9PP0YIq7/V1uPLs2c4J7pxac+4UMZ2LxP1fEwuCxW82sB2UXlqzv2C8seyg/NlICGaBOXAWlSnwr7u7e6e/BO42887JLlODo4Zya5WJeMXeQqyH4Xfa5oTh+SWHBas+ZpDJuJOp/rFGCrk8BkIWfKMSiReBL7QoSlTDTu5ZQgMy+gYuAt+iqAsbh74cLtvXvIyEiqfqy11XCNEqO3ZmvwLr1LcFntqMEq2IuRqb70tPjskQC/N0kIoKdLJ7l4+6R2iZZSN8Vv7MI+Ja5A9rEzASyzHRYuczV+MixPWONx6fZbDxEfxyA/PrCVUssNMZzVCkYI3heJN4giWLkxXfhcjCHa72eEIQPURiN8nfAVqMbA2hL0BIsA4KaL3u7SdJB79DNqpIp8skllwwBGxnlURIfXuJ9e27Pm6hSaAUgjWwwLhdJx9kQMFxV3g/fCY2HbftGlJ+vP969XU1PShIE89VH6R16FT9P4h42gU5lIYmopUSixPWgc1C3WzkM6cm5PCaq7u1qd0y+O6a79pf1yBuNaRzDJIOsv9RagCrTVDPwgc/EGKhNJZbMf8YurgzqAcRD4BZHxLADQUqwp9aOA8=
conda_forge_output_validation: true
